name: Spotless Check and Apply

on:
  pull_request:
    branches: [ "main" ]

jobs:
  spotless:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Format Code
        run: ./gradlew spotlessApply

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Formatted Code"